FoxieAdminBundle:
    resource: "@FoxieAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

FoxiePodcastsBundle:
    resource: "@FoxiePodcastsBundle/Resources/config/routing.yml"
    prefix:   /podcasts

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
