parameters:
#    foxie_podcasts.example.class: Foxie\PodcastsBundle\Example

services:
#    foxie_podcasts.example:
#        class: %foxie_podcasts.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
